name: Postman_CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.x'

    - name: Install Newman CLI
      run: npm install -g newman
              npm install -g newman-reporter-slackreporter

              npm install -g newman-reporter-htmlextra

    - name: Run Postman tests
      run: newman run "Go_REST.postman_collection.json" -e "Test_env.postman_environment.json" -r cli,htmlextra-export testArtifacts/htmlreport.html

    - name: Output the results
      uses: actions/upload-artifact@v3
      with:
        name: Reports
        path: testArtifacts
