name: Postman_CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # update Node.js to the latest version
        

      # Install Newman CLI
      - name: Install Newman
        run: npm install -g newman

      # Install htmlextra-export reporter
      - name: Install htmlextra-export reporter
        run: |
          npm install -g newman-reporter-htmlextra
          npm install reportportal-client
         

      # Run Postman tests
      - name: Run Postman tests and report to Report Portal
        run: |
         newman run "Go_REST.postman_collection.json" -e "Test_env.postman_environment.json" 
          
      - name: Send test results to Report Portal
        run: |
        
            endpoint: 'http://nashtech-test-reportportal.eastasia.cloudapp.azure.com:8080',
            apiKey: 'report_7QbUgJvxQomWUspSTzLoBTVnncIDDr6ffzlO_7-_dhAQZbBWJsghBlhDOqHSIyLB',
            project: 'automation',
            launch: 'RENU'
