name: Postman_CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Newman
      run: npm install -g newman

    - name: Install htmlextra-export reporter
      run: npm install -g newman-reporter-htmlextra

    - name: List files in directory
      run: ls -R

    - name: Run Postman tests
      run: |
        newman run "Go_REST.postman_collection.json" -e "Test_env.postman_environment.json" -r htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html
      working-directory: ${{ github.workspace }}

    - name: Output the results
      uses: actions/upload-artifact@v3
      with:
        name: Reports
        path: testArtifacts
